services:
  db:
    image: mysql:8
    container_name: shvirtd_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: example
      MYSQL_USER: app
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.20.0.10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:  # добавляем healthcheck для правильной работы depends_on
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


  app:
   # build:
   #   context: .
   #   dockerfile: Dockerfile.python
    image: myapp:latest
    container_name: shvirtd_app
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: example
      TABLE_NAME: requests_table
      MYSQL_SSL_MODE: DISABLED
    depends_on:
      - db
    expose:
      - "5000"
    #network_mode: "host"
    networks:
      app_net:
        ipv4_address: 172.20.0.5 
    restart: unless-stopped

  haproxy:
    image: haproxy:2.9
    container_name: shvirtd_haproxy
    depends_on:
      - app
    volumes:
      - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    restart: unless-stopped



  nginx:
    image: nginx:1.27
    container_name: shvirtd_nginx
    depends_on:
      - haproxy
    network_mode: "host"
    volumes:
      - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped




networks:
  app_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
      #  - gateway: 172.20.0.1