services:
  db:
    image: mysql:8
    container_name: shvirtd_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: app
      MYSQL_PASSWORD: very_strong
    ports:
      - "3306:3306"
    networks:
      - app_net
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: shvirtd_app
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: very_strong
      DB_NAME: example
      TABLE_NAME: requests_table
      MYSQL_SSL_MODE: DISABLED
    depends_on:
      - db
    expose:
      - "5000"
    networks:
      app_net:
        ipv4_address: 172.20.0.5
    restart: unless-stopped

  haproxy:
    image: haproxy:2.9
    container_name: shvirtd_haproxy
    depends_on:
      - app
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8090:8090"
    networks:
      - app_net
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    container_name: shvirtd_nginx
    depends_on:
      - haproxy
    network_mode: "service:haproxy"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  app_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
